spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test
    username: sa
    password:

  # jpa??
  jpa:
    hibernate:
      ddl-auto: create
    properties: # property ?? ??
      hibernate: # hibernate property ??
        format_sql: true

# ?? ?? ??
logging:
  level:
    # hibernate ? ??? ?? ??? debug??? ??
    # jpa hibernate? ???? sql? ??? ??? ???? ?? ??
    org.hibernate.SQL: debug
    org.hibernate.type: trace # ?? ???? ????? ???? ??